############################
## CHANGE THESE
############################

baseURL: 'https://dillondesilva.github.io/dillondesilva.github.io'
title: dillondesilva.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


