############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Resume
  url: /resume/
  weight: 30
- name: About
  url: /about/
  weight: 40
- name: Blog
  url: https://dillondesilva.github.io/thoughtdump
  weight: 50